services:
  backend:
    build: ./backend
    container_name: orgarhythmus-backend
    ports:
      - "9000:8000"   # host:container (Cloudflare -> localhost:9000)
    env_file:
      - .env
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,backend,orgarhythmus.org,www.orgarhythmus.org,api.orgarhythmus.org
    command: >
      sh -c "python manage.py migrate &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120"

  frontend:
    build: ./frontend
    container_name: orgarhythmus-frontend
    ports:
      - "8081:80"     # host:container (Cloudflare -> localhost:8081)
    depends_on:
      - backend #
